---
title: "bar"
author: "wangzhefeng"
date: "June 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(reshape2)
```

# 1.单数据系列柱形图/条形图

## 1.1 

### 1.1.1 

```{r}
mydata <- data.frame(Cut = c("Fair", "Good", "Very Good", "Premium", "Ideal"),
                     Price = c(4300, 3800, 3950, 4700, 3500))

ggplot(data = mydata, mapping = aes(x = Cut, y = Price)) +
    geom_bar(stat = "identity", position = "identity",
             width = 0.8, size = 0.25, 
             colour = "black", fill = "#FC4E07", 
             alpha = 1)
```


### 1.1.2

```{r}
mydata <- data.frame(Cut = c("Fair", "Good", "Very Good", "Premium", "Ideal"),
                     Price = c(4300, 3800, 3950, 4700, 3500))

ggplot(data = mydata, mapping = aes(x = Cut, y = Price)) +
    geom_bar(stat = "identity", position = "identity",
             width = 0.8, size = 0.25, 
             colour = "black", 
             fill = "#FC4E07", 
             alpha = 1) +
    coord_flip()
```

## 1.2 

### 1.2.1

```{r}
mydata <- data.frame(Cut = c("Fair", "Good", "Very Good", "Premium", "Ideal"),
                     Price = c(4300, 3800, 3950, 4700, 3500))
mydata$Cut <- factor(mydata$Cut, levels = c("Fair", "Good", "Very Good", "Premium", "Ideal"))

ggplot(data = mydata, mapping = aes(x = Cut, y = Price)) +
    geom_bar(stat = "identity", position = "identity", 
             width = 0.8, size = 0.25, 
             colour = "black", 
             fill = "#FC4E07", 
             alpha = 1)
```

### 1.2.2

```{r}
mydata <- data.frame(Cut = c("Fair", "Good", "Very Good", "Premium", "Ideal"),
                     Price = c(4300, 3800, 3950, 4700, 3500))
mydata$Cut <- factor(mydata$Cut, levels = c("Fair", "Good", "Very Good", "Premium", "Ideal"))

ggplot(data = mydata, mapping = aes(x = Cut, y = Price)) +
    geom_bar(stat = "identity", position = "identity", 
             width = 0.8, size = 0.25, 
             colour = "black", 
             fill = "#FC4E07", 
             alpha = 1) +
    coord_flip()
```

## 1.3 

### 1.3.1 

```{r}
mydata <- data.frame(Cut = c("Fair", "Good", "Very Good", "Premium", "Ideal"),
                     Price = c(4300, 3800, 3950, 4700, 3500))
order <- sort(mydata$Price, index.return = TRUE, decreasing = TRUE)
mydata$Cut <- factor(mydata$Cut, levels = mydata$Cut[order$ix])

ggplot(data = mydata, mapping = aes(x = Cut, y = Price)) +
    geom_bar(stat = "identity", position = "identity",
             width = 0.8, size = 0.25, 
             colour = "black", 
             fill = "#FC4E07", 
             alpha = 1)
```

### 1.3.2

```{r}
mydata <- data.frame(Cut = c("Fair", "Good", "Very Good", "Premium", "Ideal"),
                     Price = c(4300, 3800, 3950, 4700, 3500))
order <- sort(mydata$Price, index.return = TRUE, decreasing = TRUE)
mydata$Cut <- factor(mydata$Cut, levels = mydata$Cut[order$ix])

ggplot(data = mydata, mapping = aes(x = Cut, y = Price)) +
    geom_bar(stat = "identity", position = "identity",
             width = 0.8, size = 0.25, 
             colour = "black", 
             fill = "#FC4E07", 
             alpha = 1) +
    coord_flip()
```

# 2. 多数据系列柱形图/条形图

## 2.1

### 2.1.1

```{r}
mydata <- read.csv("/Users/zfwang/project/DataVisualiztion/charts/bar/data/MultiColumn_Data.csv")

ggplot(data = mydata, mapping = aes(x = Catergory, y = value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge", 
             colour = "black", width = 0., size = 0.25)
```

### 2.1.2

```{r}
mydata <- read.csv("/Users/zfwang/project/DataVisualiztion/charts/bar/data/MultiColumn_Data.csv")

ggplot(data = mydata, mapping = aes(x = Catergory, y = value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge", 
             colour = "black", width = 0., size = 0.25) +
    coord_flip()
```


## 2.2

### 2.2.1

```{r}
mydata <- read.csv(path + "/data/MultiColumn_Data.csv", check.names = FALSE)
order = sort(mydata$"1996", index.return = TRUE, decreasing = TRUE)
mydata$Catergory <- factor(mydata$Catergory, levles = mydata$Catergory[order$ix])

ggplot(data = mydata, mapping = aes(x = Catergory, y = value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge",
             colour = "black", width = 0.7, szie = 0.25)
```

### 2.2.2


```{r}
mydata <- read.csv(path + "/data/MultiColumn_Data.csv", check.names = FALSE)
order = sort(mydata$"1996", index.return = TRUE, decreasing = TRUE)
mydata$Catergory <- factor(mydata$Catergory, levles = mydata$Catergory[order$ix])

ggplot(data = mydata, mapping = aes(x = Catergory, y = value, fill = variable)) +
    geom_bar(stat = "identity", position = "dodge",
             colour = "black", width = 0.7, szie = 0.25) +
    coord_flip()
```

# 3.堆积柱形图

## 3.1

### 3.1.1

```{r}
mydata = read.csv(path + "/data/StackedColumn_Data.csv")

ggplot(data = mydata, mapping = aes(x = variable, y = value, fill = Clarity)) +
    geom_bar(stat = "identity", position = "stack", 
             colour = "black", width = 0.7, size = 0.25)
```

### 3.1.2

```{r}
mydata = read.csv(path + "/data/StackedColumn_Data.csv")

ggplot(data = mydata, mapping = aes(x = variable, y = value, fill = Clarity)) +
    geom_bar(stat = "identity", position = "stack", 
             colour = "black", width = 0.7, size = 0.25) +
    coord_flip()
```


## 3.2

### 3.2.1

```{r}
mydata = read.csv(path + "/data/StackedColumn_Data.csv")
order = sort(colSums(mydata[, 2:ncol(mydata)]), index.return = TRUE, decreasing = TRUE)
mydata = mydata[, c(1, order$ix)]
mydata$Clarity = factor(mydata$Clarity, levels = mydata$Clarity[c(1:5)])

ggplot(data = mydata, mapping = aes(x = variable, y = value, fill = Clarity)) +
    geom_bar(stat = "identity", position = "stack", 
             colour = "black", width = 0.7, size = 0.25)
```

### 3.2.2

```{r}
mydata = read.csv(path + "/data/StackedColumn_Data.csv")
order = sort(colSums(mydata[, 2:ncol(mydata)]), index.return = TRUE, decreasing = TRUE)
mydata = mydata[, c(1, order$ix)]
mydata$Clarity = factor(mydata$Clarity, levels = mydata$Clarity[c(1:5)])

ggplot(data = mydata, mapping = aes(x = variable, y = value, fill = Clarity)) +
    geom_bar(stat = "identity", position = "stack", 
             colour = "black", width = 0.7, size = 0.25) +
    coord_flip()
```

#  4.百分比堆积柱形图/条形图

## 4.1

### 4.1.1

```{r, eval = False}
ggplot(data = mydata, mapping = ase(x = , y = , fill = )) +
    geom_bar(stat = "identity", position = "fill", 
             colour = "black", width = 0.7, size = 0.25)
```

### 4.1.2


## 4.2

### 4.2.1


### 4.2.2
