---
title: "hist"
author: "wangzhefeng"
date: "June 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
```

```{r}
df = read.csv("/home/wangzhefeng/project/DataVisualiztion/charts/hist/data/Hist_Density_Data.csv",
              stringsAsFactors = FALSE)
```


# 1.统计直方图

```{r}
df_single = df %>% 
    filter(Location == "Adelaide")

ggplot(data = df_single, mapping = aes(x = MXSPD)) + 
    geom_histogram(binwidth = 1, bins = 10,
                   alpha = 0.55, colour = "black", fill = "#FC4E07", size = 0.25)
```


```{r}
df_single = df %>% 
    filter(Location == "Brisbane")

ggplot(data = df_single, mapping = aes(x = MXSPD)) + 
    geom_histogram(binwidth = 1, bins = 10,
                   alpha = 0.55, colour = "black", fill = "#FC4E07", size = 0.25)
```


```{r}
df_single = df %>% 
    filter(Location == "Melbourne")

ggplot(data = df_single, mapping = aes(x = MXSPD)) + 
    geom_histogram(binwidth = 1, bins = 10,
                   alpha = 0.55, colour = "black", fill = "#FC4E07", size = 0.25)
```


```{r}
ggplot(data = df, mapping = aes(x = MXSPD, fill = Location)) +
    geom_histogram(binwidth = 1, bins = 10, 
                   alpha = 0.5, colour = "black", size = 0.25)
```

# 2.核密度估计图

```{r}
df_single = df %>% 
    filter(Location == "Adelaide")
ggplot(data = df_single, mapping = aes(x = MXSPD)) +
    geom_density(alpha = 0.5, bw = 1, colour = "black", size = 0.25)
```


```{r}
df_single = df %>% 
    filter(Location == "Brisbane")
ggplot(data = df_single, mapping = aes(x = MXSPD)) +
    geom_density(alpha = 0.5, bw = 1, colour = "black", size = 0.25)
```


```{r}
df_single = df %>% 
    filter(Location == "Melbourne")
ggplot(data = df_single, mapping = aes(x = MXSPD)) +
    geom_density(alpha = 0.5, bw = 1, colour = "black", size = 0.25)
```

```{r}
ggplot(data = df, mapping = aes(x = MXSPD, fill = Location)) +
    geom_density(alpha = 0.5, bw = 1, colour = "black", size = 0.25)
```

# 3.核密度峰峦图

```{r}

```