---
title: "点图"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(reshape2)
```

# 不等宽柱形图

```{r}
library(ggplot2)
mydata = data.frame(Name = paste0("Project", 1:5),
                    Scale = c(35, 30, 20, 10, 5),
                    ARPU = c(56, 37, 63, 57, 59))
# 构造矩形X轴的最小点
mydata$xmin = 0
for (i in 2:5) {
    mydata$xmin[i] = sum(mydata$Scale[1:i-1])
}
# 构造矩形X轴的最大点
for (i in 1:5) {
    mydata$xmax[i] = sum(mydata$Scale[1:i])
}
# 构造数据标签的横坐标
for (i in 1:5) {
    mydata$label[i] = sum(mydata$Scale[1:i]) - mydata$Scale[i] / 2
}

ggplot(data = mydata) +
    geom_rect(mapping = aes(xmin = xmin, xmax = xmax, 
                            ymin = 0, ymax = ARPU, 
                            fill = Name), 
              colour = "black", size = 0.25) +
    geom_text(mapping = aes(x = label, y = ARPU + 3, label = ARPU), 
              size = 4, colour = "black") +
    geom_text(mapping = aes(x = label, y = -2.5, label = Name), 
              size = 4, colour = "black")
```

# 点图

```{r}
# 棒棒糖图(lollipop chart)
mydata = read.csv("/Users/zfwang/project/DataVisualiztion/charts/bar/data/DotPlots_Data.csv", 
                  sep = ",", 
                  na.strings = "NA", 
                  stringsAsFactors = FALSE)
mydata$sum = rowSums(mydata[, 2:3])
order = sort(mydata$sum, index.return = TRUE, decreasing = FALSE)
mydata$City = factor(mydata$City, levels = mydata$City[order$ix])

ggplot(data = mydata, mapping = aes(x = sum, y = City)) +
    geom_point(shape = 21, size = 3, colour = "black", fill = "#FC4E07") +
    geom_segment(mapping = aes(x = 0, xend = sum, 
                               y = City, yend = City))


# 克利夫兰点图(Cleveland's dot plot)
mydata = read.csv("/Users/zfwang/project/DataVisualiztion/charts/bar/data/DotPlots_Data.csv", 
                  sep = ",", 
                  na.strings = "NA", 
                  stringsAsFactors = FALSE)
mydata$sum = rowSums(mydata[, 2:3])
order = sort(mydata$sum, index.return = TRUE, decreasing = FALSE)
mydata$City = factor(mydata$City, levels = mydata$City[order$ix])

ggplot(data = mydata, mapping = aes(x = sum, y = City)) +
    geom_point(shape = 21, size = 3, colour = "black", fill = "#FC4E07")



# 哑铃图(dumbbell plot)
mydata = read.csv("/Users/zfwang/project/DataVisualiztion/charts/bar/data/DotPlots_Data.csv", 
                  sep = ",", 
                  na.strings = "NA", 
                  stringsAsFactors = FALSE)
mydata$City = factor(mydata$City, levels = mydata$City[order(mydata$Female)])
mydata = melt(mydata, vars = "City")

ggplot(data = mydata, mapping = aes(x = value, y = City, fill = factor(variable))) +
    geom_point(shape = 21, size = 3, colour = "black") +
    scale_fill_manual(values = c("#00AFBB", "#FC4E07", "#36BED9")) +
    geom_line(mapping = aes(group = City)) +
    theme(legend.position = c(0.85, 0.12))
```


# 