---
title: "waffle"
author: "wangzhefeng"
date: "June 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(RColorBrewer)
```


# 1.

```{r}
# data
categ_table = round(table(mpg$class) * (10 * 10) / length(mpg$class))
sort_table = sort(categ_table, index.return = TRUE, decreasing = FALSE)
Order = sort(as.data.frame(categ_table)$Freq, index.return = TRUE, decreasing = FALSE)
df = expand.grid(y = 1:10, x = 1:10)
df$category = factor(rep(names(sort_table), sort_table), levels = names(sort_table))
head(df, 20)
```


```{r}
Colormap = brewer.pal(length(sort_table), "Set2")

ggplot(data = df, aes(x = y, y = x, fill = category)) +
    geom_tile(color = "white", size = 0.25) +
    coord_fixed(ratio = 1) +
    scale_x_continuous(trans = "reverse") +
    scale_y_continuous(trans = "reverse") +
    scale_fill_manual(name = "Category", values = Colormap) +
    theme(panel.background = element_blank(),
          plot.title = element_text(size = rel(1.2)),
          legend.position = "right")
```


# 2.

```{r}
Colormap = brewer.pal(length(sort_table), "Set2")

ggplot(data = df, aes(x = y, y = x, fill = category)) +
    geom_point(color = "black", shape = 21, size = 6) +
    coord_fixed(ratio = 1) +
    scale_x_continuous(trans = "reverse") +
    scale_y_continuous(trans = "reverse") +
    scale_fill_manual(name = "Category", values = Colormap) +
    theme(panel.background = element_blank(),
          plot.title = element_text(size = rel(1.2)),
          legend.position = "right")
```